spring:
  application:
    name: smart-route

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  liquibase:
    enabled: true
    change-log: db/changelog/changeLog-master.yaml

um:
  warsaw:
    api-key: ${UM_WARSAW_API_KEY}
    base-url: https://api.um.warszawa.pl
    timetable:
      resource-path: api/action/dbtimetable_get
      timetable-id: e923fa0e-d96c-43f9-ae6e-60518c9f3238
      bus-line-id: 88cd555f-6f31-43ca-9de4-66c479ad5942
    store:
      resource-path: api/action/dbstore_get
      stop-info-id: ab75c33d-3a26-4342-b36a-6e5fef0a3ac3